[build]
builder = "RAILPACK"

[start]
command = "go build -o server server.go && ./server -port $PORT"

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
