[build]
builder = "RAILPACK"
buildCommand = "npm install && npm run build"

[start]
command = "go build -o server server.go && ./server -port $PORT"

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
multiRegionConfig = {"europe-west4-drams3a":{"numReplicas":1}}
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
