import type { Metadata } from "next";
import "./globals.css";
import Cookies from "@/components/defaults/Cookies";
import Script from "next/script";
import Navbar from "@/components/navigation/Navbar";
import Footer from "@/components/navigation/Footer";
import { Partytown } from "@builder.io/partytown/react";

export const metadata: Metadata = {
  metadataBase: new URL("https://acme.com"),
  alternates: {
    canonical: "/",
  },
  title: "Default title",
  description: "Generated by create next app",

  generator: "Next.js",
  applicationName: "Test Next",
  keywords: [""],
  authors: [
    { name: "Talesign" },
    { name: "Oliviero Taleghani", url: "https://talesign.com" },
  ],
  creator: "Oliviero Taleghani",
  publisher: "Talesign",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="it">
      <head></head>
      <body id="body">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
